server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wbhglfei/spring-config-server-config
          searchPaths: configs
          username: username
          password: password

eureka:
  client:
    serviceUrl:
      defaultZone: http://peer2:8769/eureka//