server:
  port: 8573

spring:
  application:
    name: service-lucy

eureka:
  client:
    serviceUrl:
      defaultZone: http://peer2:8769/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"